name: Build / Test / Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run prepare

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint:ci